# Generated by Django 5.1.4 on 2025-01-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerPathStudents_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='student',
        ),
        migrations.DeleteModel(
            name='CareerTrajectory',
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
