# Generated by Django 5.1.4 on 2025-01-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerPathStudents_app', '0002_remove_studentdata_student_delete_careertrajectory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
